### PR TITLE
Added healthcheck timeout support.

### PR DESCRIPTION
**Pull request by mmusnjak**
Added a timeout option to cluster healthcheck. In cases when client was completely cut off from Cassandra, the times for generating healthcheck responses were very long.

### CODE REVIEW

**Comment by stuartgunter** [comment]
Thanks for this.

Out of interest... wouldn't it be safer to have the health check use the same timeouts as any other query? otherwise you might get a situation where the app reports unhealthy when it's actually healthy by typical usage standards?

On a similar note, what about defaulting the timeout or making it optional?

**Comment by mmusnjak** [comment]
In our case this timeout is more bound to the monitoring side of things, and we don't treat this as an incident, just a warning. Timeouts for other queries are different per application and will eventually raise an incident. The problem is that dw does not return partial results, it waits for all healthchecks to complete, and so our monitoring gives up on the wait...

When you mention defaulting or making the timeout optional, you mean performing a sync query when the parameter is not set? Or just setting it by default to some very large value?

**Comment by stuartgunter** [comment]
Thanks, that makes sense.

My previous comment about default / optional was just to ensure backwards compatibility with existing clients. I actually misread your commit, where I see you've already provided a default value of `2 seconds` - sorry about that. Do you know if this is the same timeout value currently used, or if the timeout could be derived from other config if not explicitly set? In other words, how can we include this new feature without breaking / changing the behaviour for existing clients?

On that note, please could you update the README to include the new config option.

**Comment by mmusnjak** [comment]
I ran into the issue when testing a network failure scenario on a six-node cluster with two seeds configured, and I think the result came back after 30 seconds. There were no non-default settings for the connections, and I didn't test if this was dependent on the number of hosts/seeds or not.

The readme and javadoc are now also updated. The default is still at 2 seconds. It probably makes sense to keep the value fairly low, since DW executes health checks sequentially.

**Comment by stuartgunter** [comment]
Thanks. The last commit seems to have messed up formatting, so it's pretty hard to see what has changed. Please could you reinstate the original formatting and I'll merge it in?

**Comment by mmusnjak** [comment]
Sorry about that, this should be better!

**Comment by stuartgunter** [comment]
FYI... this change has just been released under version `2.2-dw0.9-cs2.1` and should appear in Maven Central sometime this evening.

**Pull request merged**
