### PR TITLE
Load balancing support

### PR DESCRIPTION
**Pull request by adejanovski**
I've added load balancing policies support in order to handle complex multi DC scenarios and rely on the Datastax Java Driver for handling it.

All LB policies should be available even those with combinations of nested policies and typed parameters.
Some examples : 

```
  loadBalancingPolicy: TokenAwarePolicy(DCAwareRoundRobinPolicy("DC1"))
  loadBalancingPolicy: DCAwareRoundRobinPolicy('DC1')
  loadBalancingPolicy: RoundRobinPolicy()
  loadBalancingPolicy: LatencyAwarePolicy(TokenAwarePolicy(RoundRobinPolicy()),(double)10.5,(long)1,(long)10,(long)1,10)
  loadBalancingPolicy: com.company.package.CustomPolicy()
```

The code was taken from the Cassandra JDBC Driver implementation that relies on the Datastax Java Driver : https://github.com/adejanovski/java-driver/tree/2.1/driver-jdbc

On a side note, have you considered using CCM for unit testing, because your test suite is a bit complex to reproduce (you have to watch all yml files to deduce the corresponding clusters, unless I'm missing something).
The Datastax Java driver team uses a class they made to build ephemeral and reproducible clusters from Java using CCM underneath through system calls : https://github.com/adejanovski/java-driver/blob/2.1/driver-core/src/test/java/com/datastax/driver/core/CCMBridge.java

I could add it to your test suite if you wish to switch to this.

### CODE REVIEW

**Comment by stuartgunter** [comment]
Thanks for the PR. It's definitely a good idea to support load balancing through configuration, so I'm entirely supportive of the idea.

The use of reflection is a concern as it's very error-prone and doesn't give the user clear feedback on what they've done wrong. Dropwizard already supports typed polymorphic configuration (examples in `dropwizard-cassandra` include `RetryPolicyFactory`, `ReconnectionPolicyFactory` and `AuthProviderFactory`). It is much easier for users to use YAML config in this way than to essentially write Java as a string. Whenever we can use the type system to enforce anything, I'd much rather use that.

I've added load balancing support to the `master` branch using the polymorphic configuration approach, and would really appreciate your feedback - especially if you notice bugs or areas that are not very clear.

On your suggestion about testing and CCM, I'm not sure how CCM would help with the YAML files. Those files are Dropwizard config files that would be required regardless of the tool used to spin up Cassandra. You do not need to watch all the YAML files... a test corresponds to a single file (the one exception to this is the smoke tests). If you start at the test, rather than the YAML files, it should be clear which one is relevant (and your IDE will probably allow you to navigate directly to that file).

That said... I'm not an expert in CCM, so it'd be great if you could explain how CCM could improve the test suite. Perhaps a small example? I'm keen to improve the tests, so any improvements that can be made here would be most welcome.

**Comment by adejanovski** [comment]
Hi Stuart,

your solution is indeed more consistent with what you've done so far on retry and reconnection policies and yaml syntax. 

I guess it is fair trading full support of load balancing policies (even custom ones or those that aren't yet integrated in the java driver) for a yaml compliant solution that avoids hacking our way through reflection.

CCM could help dynamically creating the test clusters the way they are expected and create multi node / multi DC scenarios.
It can also provide a simple way to test various cassandra releases dynamically (and validate 2.0.* and 2.1.* in a simple way). 
But I managed to run the test suite by just creating a missing "bundle" KS so this is no major concern.

I've quickly tested your new version and so far it works just fine.

Thanks for adding LB support so quickly.

**Comment by stuartgunter** [comment]
> I guess it is fair trading full support of load balancing policies (even custom ones or those that aren't yet integrated in the java driver)

I'm not sure I follow... what support is lacking from this implementation? Every `LoadBalancingPolicy` has full support in YAML, and there's the ability to use custom policies in the same way. Please could you explain?

**Comment by adejanovski** [comment]
My bad, I missed the ability to declare custom policies.

You dealt with lb policies in a very nice way, and it suits all my current needs.

Thanks again

**Comment by stuartgunter** [comment]
Version `1.1-dw0.8-cs2.1` containing these features has just been released.

http://search.maven.org/#artifactdetails%7Corg.stuartgunter%7Cdropwizard-cassandra%7C1.1-dw0.8-cs2.1%7Cjar

**Pull request closed without merging**
